# Generated by Django 5.2.8 on 2026-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Hayoti va ijodi')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Asar nomi')),
                ('txt_file', models.FileField(upload_to='asarlari/', verbose_name='TXT fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
