# Generated by Django 5.2.9 on 2026-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usmon_nosir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name': 'Biografiya', 'verbose_name_plural': 'Biografiya'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asar', 'verbose_name_plural': 'Asarlar'},
        ),
    ]
